name: Release Go Binaries

on:
  push:
    tags:
      - 'bearprint-cli-v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#bearprint-cli-v}" >> $GITHUB_ENV

      - name: Build
        working-directory: ./bearprint-cli
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -ldflags "-X main.version=${VERSION}" \
            -o bearprint-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bearprint-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bearprint-cli/bearprint-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/**/*
